project:
  type: website
  output-dir: docs

website:
  title: "The Gradient Dissident"
  navbar:
    right:
      - text: "Blog"
        href: blog.html
      - icon: github
        href: https://github.com/Jonathanmoatti
      - icon: linkedin
        href: https://www.linkedin.com/in/jonathan-moatti/

format:
  html:
    theme:
      - cosmo
      - brand
    highlight-style: github-dark
    css: styles.css

listing:
  contents: "posts/local_agents"
  sort: "date desc"
  type: default