project:
  type: website
  output-dir: docs

website:
  title: "Gradient Dissent"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/jonathan-moatti/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



