project:
  type: website
  output-dir: docs

website:
  title: "Gradient Dissent"
  navbar:
    right:
      - text: "Blog"
        href: blog.html
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/jonathan-moatti/
format:
  html:
    theme:
      dark: [cosmo, brand]
    css: styles.css